//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab8.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lab8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично! Я же бот..
        /// </summary>
        internal static string allrightMsg {
            get {
                return ResourceManager.GetString("allrightMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на rostov-on-don.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на . Ужасно холодно на улице!Лучше сидеть дома..
        /// </summary>
        internal static string coldMsg {
            get {
                return ResourceManager.GetString("coldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Глупый бот не понимать. Пните разработчиков :(.
        /// </summary>
        internal static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет, я - твой бот-помощник. Скажи, как тебя зовут, твой курс и группу, тогда я смогу быть тебе полезным :).
        /// </summary>
        internal static string greetingMsg {
            get {
                return ResourceManager.GetString("greetingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я могу узнать Ваше расписание,  рассказать, чем можно подкрепиться в столовой,  подсказать часы работы деканата, узнать для Вас погоду..
        /// </summary>
        internal static string helpMsg {
            get {
                return ResourceManager.GetString("helpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приятно познакомиться,.
        /// </summary>
        internal static string ntmyMsg {
            get {
                return ResourceManager.GetString("ntmyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окей, запомнил!.
        /// </summary>
        internal static string okayMsg {
            get {
                return ResourceManager.GetString("okayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможен дождь! Захватите зонтик :).
        /// </summary>
        internal static string rainMsg {
            get {
                return ResourceManager.GetString("rainMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможен снег! По пути можно играть в снежки! :).
        /// </summary>
        internal static string snowMsg {
            get {
                return ResourceManager.GetString("snowMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  C. Отличная погода, чтобы идти на пары!.
        /// </summary>
        internal static string studyMsg {
            get {
                return ResourceManager.GetString("studyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дождя не ожидается..
        /// </summary>
        internal static string sunnyMsg {
            get {
                return ResourceManager.GetString("sunnyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C. Отличная погода, чтобы погулять..
        /// </summary>
        internal static string warmMsg {
            get {
                return ResourceManager.GetString("warmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 522ea52cffe0c78955e0e319e1572a7b.
        /// </summary>
        internal static string wmKey {
            get {
                return ResourceManager.GetString("wmKey", resourceCulture);
            }
        }
    }
}
