//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab8.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("lab8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я бот,прилетевший с планеты Фаэтон. Я появился на свет в 2347 году. Моим создателем был некий человек по имени Джон Конор, а точнее его галограмма из прошлого. Я был призван прилететь на Вашу планету и защищать Вас, землян, от грядущей опасности!.
        /// </summary>
        internal static string aboutSelf {
            get {
                return ResourceManager.GetString("aboutSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отлично! Я же бот..
        /// </summary>
        internal static string allrightMsg {
            get {
                return ResourceManager.GetString("allrightMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ну раз понятно, тогда я пошёл пить чай!.
        /// </summary>
        internal static string allUnderstand {
            get {
                return ResourceManager.GetString("allUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Досвидания, человек!.
        /// </summary>
        internal static string bayMsg {
            get {
                return ResourceManager.GetString("bayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всё будет отлично! Не унывай!.
        /// </summary>
        internal static string careMsg {
            get {
                return ResourceManager.GetString("careMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на rostov-on-don.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на . Ужасно холодно на улице!Лучше сидеть дома..
        /// </summary>
        internal static string coldMsg {
            get {
                return ResourceManager.GetString("coldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В скором времени,на Вашу планету прилетят межпланетарные захватчики. Они хотят заполучить Вашу планету в качестве сырья для создания своего оружия, так как на Вашей планете очень много полезных ископаемых.  Они будут использовать людей в качестве бесплатной рабочей силы на своё благо. .
        /// </summary>
        internal static string danger {
            get {
                return ResourceManager.GetString("danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Глупый бот не понимать. Пните разработчиков :(.
        /// </summary>
        internal static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет, я - твой бот-помощник. Скажи, как тебя зовут, твой курс и группу, тогда я смогу быть тебе полезным :).
        /// </summary>
        internal static string greetingMsg {
            get {
                return ResourceManager.GetString("greetingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я могу узнать Ваше расписание,  рассказать, чем можно подкрепиться в столовой,  подсказать часы работы деканата, узнать для Вас погоду, рассказать последние актуальные новости..
        /// </summary>
        internal static string helpMsg {
            get {
                return ResourceManager.GetString("helpMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Никак. Спасти человечество могу только я. Когда они ступят на Вашу землю и поглотят большую часть её территории, я проникну в серце межпланетного коробля U-019-X и выведу из строя модуль управления их миссией. После чего произовйдёт полное уничтожение врага. Человечество будет пытаться сопротивляться, но понесёт огромные потери. Это бесполезно..
        /// </summary>
        internal static string howSaving {
            get {
                return ResourceManager.GetString("howSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Джон Конор - лидер всемирного сопротивления в войне между человечеством и машинами. Он последняя надежда человечества. Он создаст меня в будущем для того, что бы я вернулся в прошлое и спас человечество от гибели..
        /// </summary>
        internal static string johnKonor {
            get {
                return ResourceManager.GetString("johnKonor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 23f744682d334ceda9267fb8fd4c4964.
        /// </summary>
        internal static string newsKey {
            get {
                return ResourceManager.GetString("newsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приятно познакомиться, .
        /// </summary>
        internal static string ntmyMsg {
            get {
                return ResourceManager.GetString("ntmyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окей, запомнил!.
        /// </summary>
        internal static string okayMsg {
            get {
                return ResourceManager.GetString("okayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможен дождь! Захватите зонтик :).
        /// </summary>
        internal static string rainMsg {
            get {
                return ResourceManager.GetString("rainMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможен снег! По пути можно играть в снежки! :).
        /// </summary>
        internal static string snowMsg {
            get {
                return ResourceManager.GetString("snowMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  C. Отличная погода, чтобы идти на пары!.
        /// </summary>
        internal static string studyMsg {
            get {
                return ResourceManager.GetString("studyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дождя не ожидается..
        /// </summary>
        internal static string sunnyMsg {
            get {
                return ResourceManager.GetString("sunnyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не за что! Я пока что не устал от Ваших вопросов..
        /// </summary>
        internal static string thnxMsg {
            get {
                return ResourceManager.GetString("thnxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C. Отличная погода, чтобы погулять..
        /// </summary>
        internal static string warmMsg {
            get {
                return ResourceManager.GetString("warmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 522ea52cffe0c78955e0e319e1572a7b.
        /// </summary>
        internal static string wmKey {
            get {
                return ResourceManager.GetString("wmKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо, я знаю !) Джон постарался).
        /// </summary>
        internal static string wowСool {
            get {
                return ResourceManager.GetString("wowСool", resourceCulture);
            }
        }
    }
}
